### ISSUE TITLE
Links are not being correctly evaluated when crawling (not being added)

### ISSUE THREAD

**Issue by cgr71ii** [transducens/linguacrawl#3]
When crawling a document, new links are discovered and the expected behaviour is to be added to a list in order to crawl them after (or not) the current document had been crawled. This expected behaviour is not working correctly.

The problem arises in `site_crawler.py`, in function `_process_link(self, link, url)`. When line `if not link.is_valid():` is reached, the returned value is `None` in some cases (all those cases which the value is not `False`, so `True` is never returned). In the file `link.py`, in function `is_valid(self):` there is an structure `if: ... return False elif: ... return False elif: ... return False if condition ... else: return True`. In the 2nd `elif` is where the `None` value is returned in those cases where `True` should be returned if any check did not lead to return `False`. In the end, the problem can be solved, if I am not wrong, replacing `else: return True` by `return True` directly.

Checked (replaced) and working as expected.

Moreover, this issue seems to be the cause of #2. With the explained fix, now when using "HTTP" I see the line `INFO:root:Thread-1 Redirect: http://www.ua.es/ -> https://www.ua.es/`

**Comment by mespla** [comment]
Fixed in commit 4deab22e9467f7c4f2671eac5e56676027b180b5
